# Alpha D1 values for kube-prometheus-stack.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

## Configuration for alertmanager
## ref: https://prometheus.io/docs/alerting/alertmanager/
##
alertmanager:
  podDisruptionBudget:
    enabled: true
    minAvailable: 1
    maxUnavailable: ""


  ## Configuration for Alertmanager service
  ##
  service:
    annotations:
      service.beta.kubernetes.io/azure-load-balancer-internal: "true"
      service.beta.kubernetes.io/azure-load-balancer-internal-subnet: "agrid-07-p1-spk-crd-aks-snet-001"
    loadBalancerIP: "10.16.161.253"
    type: LoadBalancer

  ## Settings affecting alertmanagerSpec
  ## ref: https://github.com/prometheus-operator/prometheus-operator/blob/master/Documentation/api.md#alertmanagerspec
  ##
  alertmanagerSpec:
    ## Image of Alertmanager
    ##
    image:
      repository: agrid06p1hubacr001.azurecr.io/alpha-telemetry/quay.io/prometheus/alertmanager
      sha: ""
    logFormat: json
    podAntiAffinity: "hard"
    podAntiAffinityTopologyKey: topology.kubernetes.io/zone

    ## Assign custom affinity rules to the alertmanager instance
    ## ref: https://kubernetes.io/docs/concepts/configuration/assign-pod-node/
    ##
    affinity:
      nodeAffinity:
        preferredDuringSchedulingIgnoredDuringExecution:
        - preference:
            matchExpressions:
            - key: app_pool
              operator: In
              values:
              - metricssvc
          weight: 100
    tolerations: 
      - key: "sku"
        operator: "Equal"
        value: "metricssvc"
        effect: "NoSchedule"  

grafana:
  enabled: false

## Configuration for kube-state-metrics subchart
##
kube-state-metrics:
  image:
    repository: agrid06p1hubacr001.azurecr.io/alpha-telemetry/k8s.gcr.io/kube-state-metrics/kube-state-metrics
  metricLabelsAllowlist:
  - pods=[*]
  metricAnnotationsAllowList:
  - pods=[*]    
  tolerations:
    - key: "sku"
      operator: "Equal"
      value: "metricssvc"
      effect: "NoSchedule"
  affinity:
    # nodeAffinity:
    #   requiredDuringSchedulingIgnoredDuringExecution:
    #     nodeSelectorTerms:
    #     - matchExpressions:
    #       - key: app_pool
    #         operator: In
    #         values:
    #         - metricssvc    
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:
            matchExpressions:
            - key: app.kubernetes.io/name
              operator: In
              values:
              - kube-state-metrics
          topologyKey: topology.kubernetes.io/zone    

## Configuration for prometheus-node-exporter subchart
##
prometheus-node-exporter:
  image:
    repository: agrid06p1hubacr001.azurecr.io/alpha-telemetry/quay.io/prometheus/node-exporter  

## Manages Prometheus and Alertmanager components
##
prometheusOperator:
  admissionWebhooks:
    patch:
      enabled: true
      image:
        repository: agrid06p1hubacr001.azurecr.io/alpha-telemetry/k8s.gcr.io/ingress-nginx/kube-webhook-certgen
        sha: ""
        pullPolicy: IfNotPresent

  logFormat: json

  tolerations: 
    - key: "sku"
      operator: "Equal"
      value: "metricssvc"
      effect: "NoSchedule" 

  ## Assign custom affinity rules to the prometheus operator
  ## ref: https://kubernetes.io/docs/concepts/configuration/assign-pod-node/
  ##
  affinity:
    nodeAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
      - preference:
          matchExpressions:
          - key: app_pool
            operator: In
            values:
            - metricssvc
        weight: 100

  ## Prometheus-operator image
  ##
  image:
    repository: agrid06p1hubacr001.azurecr.io/alpha-telemetry/quay.io/prometheus-operator/prometheus-operator
    sha: ""
    pullPolicy: IfNotPresent

  prometheusConfigReloader:
    # image to use for config and rule reloading
    image:
      repository: agrid06p1hubacr001.azurecr.io/alpha-telemetry/quay.io/prometheus-operator/prometheus-config-reloader
      sha: ""
  thanosImage:
    repository: agrid06p1hubacr001.azurecr.io/alpha-telemetry/quay.io/thanos/thanos      
    sha: "" 
    
prometheus:
  ## Configuration for Prometheus service
  ##
  service:
    annotations:
      service.beta.kubernetes.io/azure-load-balancer-internal: "true"
      service.beta.kubernetes.io/azure-load-balancer-internal-subnet: "agrid-07-p1-spk-crd-aks-snet-001"
    loadBalancerIP: "10.16.161.252"
    type: LoadBalancer
    sessionAffinity: ClientIP
  podDisruptionBudget:
    enabled: true
    minAvailable: 1
    maxUnavailable: ""


  prometheusSpec:
    enableAdminAPI: true
    image:
      repository: agrid06p1hubacr001.azurecr.io/alpha-telemetry/quay.io/prometheus/prometheus
      sha: ""

    tolerations:
      - key: "sku"
        operator: "Equal"
        value: "metricssvc"
        effect: "NoSchedule" 

    externalLabels:
      cluster: p1-spoke1
      region: central-us-1
    ruleSelectorNilUsesHelmValues: false
    serviceMonitorSelectorNilUsesHelmValues: false
    podMonitorSelectorNilUsesHelmValues: false
    retention: 7d
    walCompression: true
    replicas: 3
    logFormat: json

    ## Prefix used to register routes, overriding externalUrl route.
    ## Useful for proxies that rewrite URLs.
    ##
    routePrefix: /

    ## Standard object's metadata. More info: https://github.com/kubernetes/community/blob/master/contributors/devel/sig-architecture/api-conventions.md#metadata
    ## Metadata Labels and Annotations gets propagated to the prometheus pods.
    ##
    podMetadata:
      labels:
        app: prometheus-d1-spoke1
        k8s-app: prometheus-d1-spoke1

    ## Pod anti-affinity can prevent the scheduler from placing Prometheus replicas on the same node.
    ## The default value "soft" means that the scheduler should *prefer* to not schedule two replica pods onto the same node but no guarantee is provided.
    ## The value "hard" means that the scheduler is *required* to not schedule two replica pods onto the same node.
    ## The value "" will disable pod anti-affinity so that no anti-affinity rules will be configured.
    podAntiAffinity: "hard"

    ## If anti-affinity is enabled sets the topologyKey to use for anti-affinity.
    ## This can be changed to, for example, failure-domain.beta.kubernetes.io/zone
    ##
    podAntiAffinityTopologyKey: topology.kubernetes.io/zone

    ## Assign custom affinity rules to the prometheus instance
    ## ref: https://kubernetes.io/docs/concepts/configuration/assign-pod-node/
    ##
    affinity:
      nodeAffinity:
        preferredDuringSchedulingIgnoredDuringExecution:
        - preference:
            matchExpressions:
            - key: app_pool
              operator: In
              values:
              - metricssvc
          weight: 100

    storageSpec:
    # Using PersistentVolumeClaim
    #
      volumeClaimTemplate:
        spec:
          storageClassName: obs-sc
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 2Ti
